### ISSUE TITLE
Determine if implementation will be standalone, or integrate into MediaWiki

### ISSUE THREAD

**Issue by patbarron** [wplug/MemberPortal#4]
We need to determine the strategy that we will pursue to implement the portal, whether it will be a standalone implementation, or if we will attempt to integrate the functionality into MediaWiki (and leverage MediaWiki's authentication, for example).

**Comment by patbarron** [comment]
My own opinion is that we should opt to implement this as a standalone portal.  While it may be attractive to try to integrate into the existing MediaWiki deployment (since we already have that set up, and because it already provides an authentication system), we would then have to learn MediaWiki's API, and I fear potential for future MediaWiki updates breaking an add-on.  Would like to hear if there are any other opinions, though.

**Comment by jprostko** [comment]
I am fine with it being a separate implementation, as that way if we decide to ever switch out MediaWiki for another CMS, then this can just come along for the ride.  I do agree it would nice to be able to use MediaWiki's authentication though, but handling authentication shouldn't be too much more to do if we roll our own.

**Comment by patbarron** [comment]
Closing this issue, as WPLUG (as an organization) is currently defunct, and this project has been abandoned.
