### ISSUE TITLE
Define a strategy for authentication and authorization

### ISSUE THREAD

**Issue by patbarron** [wplug/MemberPortal#5]
If we implement the portal as a standalone system, we will need to decide how to do authentication (both in terms of how we will manage authentication data on the back-end, and how the UI will deal with it), and authorization (how we will keep track of who is an admin and who is not).

My immediate suggestion would be to deploy an LDAP directory, and to define a group in LDAP to list who is an admin.

What we do here is dependent on the outcome of Issue #4.

**Comment by lazypower** [comment]
:+1: on LDAP auth regardless of tech. Most modern languages have LDAP support.

**Comment by patbarron** [comment]
Closing this issue, as WPLUG (as an organization) is currently defunct, and this project has been abandoned.
