### ISSUE TITLE
Technical consideration - should code be database agnostic?

### ISSUE THREAD

**Issue by jprostko** [wplug/MemberPortal#6]
Right now we are using a MySQL-compatible database, but should the code we write be database agnostic in case we decide to switch to PostgreSQL, SQLite, or something else at a later point?

I'm asking since I'll need to know if we're going to use mysqli (which naturally only works for MySQL) or else something like PDO or Doctrine DBAL, for instance.

I'd prefer to make it agnostic since I doubt we're going to be using any MySQL-specific features, but I wanted more input about this.  Yes, it could potentially be slower to use a DBAL, but it would certainly make our lives easier later if the database backend was switched.  I suppose something like Doctrine would be nice too, as we could also add in their ORM if we desired, which utilizes their DBAL (which can be used standalone).

Any opinions?

**Comment by patbarron** [comment]
I will admit to not really knowing much about ways to abstract the DB functionality, other than implementing the portal in Rails (which just does this for you automagically).  I will have to read up on the DBALs you've mentioned.  Do you have any experience with any of them, or preferences for one DBAL over others?

**Comment by patbarron** [comment]
Alternatively, we could potentially implement the portal in Java and use JDBC to abstract the database layer.  I don't suspect we'll end up doing that...  But I guess it is an option, if we reject it perhaps we should at least document the reasoning.  I'll open a new issue on environment/framework selection so we can document that discussion there.

**Comment by jprostko** [comment]
PDO is actually not a full-blown DBAL, and I guess it's considered more like a data access abstraction layer.  In other words, it won't go rewriting SQL and implementing database-specific features.  Basically there's only certain things it will do, and you are stuck with what it can do (which is still a lot).

PDO is built into PHP and enabled on our server (at least for MySQL and SQLite), and I suspect it will be good enough for our needs if we take the PHP approach.

That said, we have other things to worry about like form validation, protection from SQL injection, etc., and instead of rolling our own facilities for that, we would likely be better off using a framework like Symfony, which comes with Doctrine DBAL and ORM out of the box anyway.

Discussion about that can go into #7 though, as the answer to that issue will essentially answer this issue at the same time.

**Comment by lazypower** [comment]
When I used PHP i was a fan of the MVC abstraction in CodeIgniter - which was a wrapper around PDO - but I do beleive that CI has become a bit long in the tooth. 

Do we have a requirements doc for what information we will be storing in said database?

**Comment by jprostko** [comment]
Well, we decided to get this all set up on Github to help with the requirements, since we knew it would be a bad idea to just start writing code without knowing our exact requirements.  There is a database schema in place currently with basic information (name, email, address, phone number, is person a current member, etc.) for users/members, but that is likely to change too as we work through how exactly everything will function as a whole.

Also, if we end up using some sort of ORM as part of this, the schema will have to change to accommodate that.

As for CI, it makes things easy, but it seems it has fallen out of favor over the years.  I'm not saying it isn't a good candidate for us (we're not making some huge enterprise application), but I kind of want to go through doing some simple things with some of the more popular MVC frameworks and come to a conclusion there if any of them are well-suited to our goals (which are still being determined).

I happen to have a decent exposure to Symfony lately since I am often digging into the concrete5 and Drupal 8 codebases, but I still want to look at other options, simply because Symfony2 can be a bit confusing for somebody that isn't familiar with it.

In any case, we should start putting together an actual requirements document, even if there's lots of information we don't know quite yet.

**Comment by lazypower** [comment]
Agreed, I just forked the repo and will send a PR against the repository with a Skeleton pre-planning doc that should help us answer some of these questions and formalize a lot of what's going on in the discussion threads here in issues. Thanks for the feedback @jprostko

**Comment by jprostko** [comment]
I'm going to dig more into the planning doc as I find time here to fill in what I can, but wanted to mention if we use any of the more popular frameworks, we'll get alternate database support for free anyway.

**Comment by patbarron** [comment]
Closing this issue, as WPLUG (as an organization) is currently defunct, and this project has been abandoned.
